from __future__ import annotations

import os
import smtplib
from email.message import EmailMessage

from langchain_core.tools import tool


TRUTHY_VALUES = {"1", "true", "yes", "on"}


def email_sending_enabled() -> bool:
    return os.getenv("ENABLE_EMAIL_SENDING", "false").strip().lower() in TRUTHY_VALUES


def smtp_settings() -> dict[str, str | int | bool]:
    return {
        "host": os.getenv("SMTP_HOST", "smtp.gmail.com"),
        "port": int(os.getenv("SMTP_PORT", "465")),
        "username": os.getenv("SMTP_USERNAME", ""),
        "password": os.getenv("SMTP_PASSWORD", ""),
        "from_email": os.getenv("SMTP_FROM", os.getenv("SMTP_USERNAME", "")),
        "use_ssl": os.getenv("SMTP_USE_SSL", "true").strip().lower() in TRUTHY_VALUES,
    }


def send_email_message(to_email: str, subject: str, body: str) -> str:
    if not email_sending_enabled():
        return (
            "Email sending is disabled. Set ENABLE_EMAIL_SENDING=true and provide SMTP_* settings "
            "before using this tool."
        )

    settings = smtp_settings()
    missing = [
        key
        for key in ("username", "password", "from_email")
        if not settings[key]
    ]
    if missing:
        return f"Email not sent. Missing SMTP settings: {', '.join(missing)}."

    if "@" not in to_email:
        raise ValueError("to_email 不是有效的 email。")

    message = EmailMessage()
    message["Subject"] = subject.strip() or "Stock agent alert"
    message["From"] = str(settings["from_email"])
    message["To"] = to_email.strip()
    message.set_content(body.strip() or "Bullish signal generated by stock agent.")

    host = str(settings["host"])
    port = int(settings["port"])
    username = str(settings["username"])
    password = str(settings["password"])

    if bool(settings["use_ssl"]):
        with smtplib.SMTP_SSL(host, port) as smtp:
            smtp.login(username, password)
            smtp.send_message(message)
    else:
        with smtplib.SMTP(host, port) as smtp:
            smtp.starttls()
            smtp.login(username, password)
            smtp.send_message(message)

    return f"Email sent to {to_email} with subject '{message['Subject']}'."


@tool
def send_email_alert(to_email: str, subject: str, body: str) -> str:
    """當你判斷某檔股票可以偏多操作且使用者提供 email 時，寄送提醒信件。收件者可為 Gmail。"""
    return send_email_message(to_email=to_email, subject=subject, body=body)


def get_email_tools() -> list[tool]:
    return [
        send_email_alert
        ]